### ISSUE TITLE
Opera support

### ISSUE THREAD

**Issue by novos7** [DominicMaas/TimelineExtension#31] opened 2018-07-14 16:58 UTC
Are you planning to release this extension for the Opera?

**Comment by da2x** [comment] 2018-07-14 21:31
No idea if @DominicMaas will bother shipping ofr Opera and uploading it to Opera Add-Ons. You’ll probably be able to install it via the Chrome Web Store with the [Chrome Extension enabler](https://addons.opera.com/en/extensions/details/install-chrome-extensions/) installed anyway.

@DominicMaas: Opera has their own extension APIs and distribute through their own website, so it should also have its own client ID.  It doesn’t support `identity.getRedirectURL()` but should otherwise be compatible with current codebase. I’m not sure of whether it expects and requires a special URL for `identity.launchWebAuthFlow()` and it [isn’t documented](https://dev.opera.com/extensions/apis/). Opera User-Agent string is the same as Chrome’s with an extra OPR component. The detection string is `OPR/` (the trailing slash is required to distinguish it from some mobile handsets). [Icon assets](http://brand.opera.com/brandbook/file/97/24dc9d51641277313344b7e297bee270/Opera_Logo_Full_Color.zip).

Vivladi has fewer users than Opera but they don’t require any work to support as it’s virtually identical to Chrome (except [one small patch](https://github.com/DominicMaas/TimelineExtension/commit/5bd1c7a27de43d27c8cee566d987c944da3e2a75)) and users install extensions for Vivladi through the Chrome Web Store.

Disclaimer: Opera Software is a former employer.

**Comment by DominicMaas** [comment] 2018-07-16 01:21
I've added the assets and browser name (so if you install it from the Chrome store, it should show the correct info).

**Comment by dmitrij-drandarov** [comment] 2018-07-17 18:13
Setup my system again today. The extension was working yesterday, now the Microsoft Authentification site that opens says:

We're unable to complete your request
Microsoft account is experiencing technical problems. Please try again later.

**Comment by DominicMaas** [comment] 2018-07-17 18:35
Ah yes, the extension is currently half broken for Opera. I'll publish 1.0.3 today with fixes for Opera (and Android).

**Comment by DominicMaas** [comment] 2018-07-17 19:53
1.0.3 has been published. Opera now uses the fallback auth system, so all that's left is publishing it to the Opera extension store.

**Comment by dmitrij-drandarov** [comment] 2018-07-17 20:11
The Chrome Store Version was updated.
Can confirm that 1.0.3 is working as intended 👍 

Thanks!

**Comment by DominicMaas** [comment] 2018-07-18 18:56
Currently pending release in the opera addons store.

**Comment by DominicMaas** [comment] 2018-08-05 05:30
Looks like Opera is moving to Chrome extensions anyway (so best to use that when it's released), or use the above extension allowing you to install chrome extensions. 

I did attempt to add the extension to the Opera Extension store, but it's been pending for 17 days now, so I've given up.

**Closed by DominicMaas** 2018-08-05 05:30 UTC

**Comment by novos7** [comment] 2018-08-05 23:28
Opera doesn't plan to upgrade to Chrome extensions. The latest developer version has made it easier for those who want to use the extensions for Chrome. Now Opera herself suggests installing an extension that makes it possible. 

I know that waiting for the release of the extension in the Opera store takes a long time, but it is an advantage over Chrome. Thanks to this, each extension is thoroughly verified and you can be sure that it does not contain malicious code.
