### ISSUE TITLE
Private Browsing websites shown in Timeline on Firefox

### ISSUE THREAD

**Issue by FireSnyper** [DominicMaas/TimelineExtension#44] opened 2018-07-16 11:24 UTC
Websites visited in Private Browsing will show up in Timeline, even though the extension says that this will not happen.

I've managed to reproduce this bug, screenshots below:
![Visited page in a Private Browsing window](https://user-images.githubusercontent.com/13640661/42756021-f56531e2-892c-11e8-9e8e-ee328ac6434c.png)
![The same page shows up in Timeline](https://user-images.githubusercontent.com/13640661/42756022-f5a3150c-892c-11e8-839c-04df02ef5176.png)

Steps to reproduce:
1) Open new Private Browsing window/tab
2) Visit any page for at least the amount of time set for a page to appear in Timeline
3) Open Timeline

Browser: Firefox 61.0.1 (64-bit)
Plugin details: v1.0.1, installed from official Mozilla Addons website (addons.mozilla.org)
Enabled extensions: uBlock Origin; BetterTTV; Reddit Enhancement Suite; Font Finder; Windows Timeline Support
OS: Windows 10 Home, Redstone 4/April 2018 Update/v1803, build 17134

**Comment by 810** [comment] 2018-07-16 12:52
should be fixed now, by today commits

**Comment by da2x** [comment] 2018-07-16 17:13
This is a duplicate of issues #39.

**Comment by DominicMaas** [comment] 2018-07-17 10:37
This fix was included in 1.0.2 (now released).

**Closed by DominicMaas** 2018-07-17 10:37 UTC
